/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";
import YourToken from "~~/generated/hardhat_contracts.json";

const deployedContracts = {
  31337: {
    YourToken: {
      address: "0xYourTokenAddress", // This will be automatically updated after deployment
      abi: YourToken.YourToken.abi,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
